export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_TOKEN_CHECK = "AUTH_TOKEN_CHECK";
export const LOGOUT = "LOGOUT";

export const TOOGLE_SIDEBAR = "TOOGLE_SIDEBAR";
export const TOOGLE_DARK_MODE = "TOOGLE_DARK_MODE";

export const CATEGORIES_REQUEST = "CATEGORIES_REQUEST";
export const CATEGORIES_SUCCESS = "CATEGORIES_SUCCESS";
export const CATEGORIES_FAILURE = "CATEGORIES_FAILURE";
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS";
export const CATEGORY_FAILURE = "CATEGORY_FAILURE";
export const SHOW_CATEGORY_SUCCESS = "SHOW_CATEGORY_SUCCESS";
export const SHOW_CATEGORY_FAILURE = "SHOW_CATEGORY_FAILURE";

export const PRODUCTS_REQUEST = "PRODUCTS_REQUEST";

export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_FAILURE = "PRODUCT_FAILURE";
